# Site settings
title: Chas Parr
email: cxp2265@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for Chas Parr
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  chasparr

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
